### PR TITLE
feat: CICD

### PR DESCRIPTION
**Pull request by ayashjorden**

### CODE REVIEW

**Comment by deanefrati** [comment]
I didn't quite understand how this does the creation of a release tag can we go over this when you have some time?

**Comment by Lutherwaves** [comment]
I found this library to be widely used in the community https://github.com/goreleaser/goreleaser-action, example - https://github.com/tink3rlabs/example-app/blob/main/.github/workflows/release.yml#L22

**Review by Lutherwaves — COMMENTED** [review]
Review

**Comment by ayashjorden** [comment]
> I found this library to be widely used in the community https://github.com/goreleaser/goreleaser-action, example - https://github.com/tink3rlabs/example-app/blob/main/.github/workflows/release.yml#L22

I'll take a look, thanks!

**Comment by ayashjorden** [comment]
> I didn't quite understand how this does the creation of a release tag can we go over this when you have some time?

In `.github/workflows/release-draft.yml` there's a matcher on tags starting with `v*`, I think that this is how its triggered upon a _release_.

I'll rework the PR to be concise and clear.

**Pull request closed without merging**
